name: story_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  provider: ^6.1.4
  lottie: ^3.3.1
  shared_preferences: ^2.5.2
  http: ^1.3.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animation/
